### ISSUE TITLE
Possibility of having a return value as an `Annotated`?

### ISSUE THREAD

**Issue by vreuter** [alimanfoo/numpydoc_decorator#45]
Hi @alimanfoo , I love this library already, especially the ability to avoid repetition with bundling parameter annotations into a `class` like you show in the README. It seems that this isn't possible for the return type/value annotation, though, as I get a `TypeError` when attempting that strategy to annotate a function return.

Would you support the addition of this capability to this package? At first blush, anyway, this seems legal and not limited by Python syntax:
```python
>>> def myfun(x: int) -> Annotated[str, Doc("return val")]:
...     pass
...

```

**Comment by vreuter** [comment]
Ah, false alarm, sorry! This was a use-site mistake 🤦

**Comment by alimanfoo** [comment]
Hi @vreuter, really cool to hear the library is useful!
